import { jsPDF } from "jspdf";
import { SOMAIYA_LOGO_DATA_URI } from "@/lib/branding";
import type { PaperSet } from "@/lib/types";

export interface ExportablePaper {
  course_code: string;
  course_name: string;
  class_name: string;
  semester_label?: string | null;
  academic_year_label?: string | null;
  exam_type: string;
  duration_minutes: number;
  max_marks: number;
  course_outcomes: string[];
  sets: PaperSet[];
}

interface ExportOptions {
  /** Exam-facing copies pass false so Course Outcomes never reach students. */
  includeCourseOutcomes: boolean;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildPaperHtml(paper: ExportablePaper, options: ExportOptions): string {
  const { includeCourseOutcomes } = options;
  const meta = [
    paper.class_name,
    paper.semester_label ? `Semester ${paper.semester_label}` : null,
    paper.academic_year_label,
    paper.exam_type,
  ]
    .filter(Boolean)
    .join(" &nbsp;•&nbsp; ");

  const outcomesBlock =
    includeCourseOutcomes && paper.course_outcomes.length
      ? `<section class="co-block">
           <h3>Course Outcomes</h3>
           <ol>${paper.course_outcomes.map((co) => `<li>${escapeHtml(co)}</li>`).join("")}</ol>
         </section>`
      : "";

  const sets = paper.sets
    .map(
      (set, index) => `
      <section class="set${index > 0 ? " page-break" : ""}">
        <h2>${escapeHtml(set.label)}${includeCourseOutcomes ? ` <span class="bt">BT ${escapeHtml(set.bt)}</span>` : ""}</h2>
        <table>
          <thead>
            <tr>
              <th class="q">Q.</th>
              <th>Question</th>
              <th class="m">Marks</th>
              ${includeCourseOutcomes ? '<th class="c">CO</th><th class="c">BT</th>' : ""}
            </tr>
          </thead>
          <tbody>
            ${set.questions
              .map(
                (q) => `<tr>
                  <td class="q">${escapeHtml(q.no)}</td>
                  <td>${escapeHtml(q.text)}</td>
                  <td class="m">${q.marks}</td>
                  ${includeCourseOutcomes ? `<td class="c">${escapeHtml(q.co)}</td><td class="c">${escapeHtml(q.bt)}</td>` : ""}
                </tr>`,
              )
              .join("")}
          </tbody>
        </table>
      </section>`,
    )
    .join("");

  return `<!doctype html>
<html><head><meta charset="utf-8"/>
<title>${escapeHtml(paper.course_code)} ${escapeHtml(paper.course_name)}</title>
<style>
  @page { margin: 18mm 16mm; }
  body { font-family: Georgia, 'Times New Roman', serif; color: #24201d; margin: 0; }
  header.sheet { display:flex; align-items:center; gap:16px; border-bottom:2px solid #7B1416; padding-bottom:10px; margin-bottom:14px; }
  header.sheet img { height:52px; }
  header.sheet .title { font-size: 15px; font-weight: 700; color:#7B1416; }
  header.sheet .sub { font-size: 12px; color:#5a4c44; }
  h1 { font-size: 18px; margin: 6px 0 2px; }
  .meta { font-size: 12px; color:#5a4c44; margin-bottom: 4px; }
  .rules { font-size: 12px; display:flex; justify-content:space-between; border-top:1px dashed #bbb; border-bottom:1px dashed #bbb; padding:6px 0; margin: 10px 0 16px; }
  h2 { font-size: 15px; margin: 18px 0 8px; }
  .bt { font-size: 11px; background:#f0e2c8; padding:2px 6px; border-radius:4px; }
  table { width:100%; border-collapse: collapse; font-size: 12.5px; }
  th, td { border:1px solid #d8cfc7; padding:6px 8px; text-align:left; vertical-align: top; }
  th { background:#f6efe6; }
  td.q, th.q { width: 44px; }
  td.m, th.m { width: 58px; text-align:center; }
  td.c, th.c { width: 52px; text-align:center; }
  .co-block { font-size:12.5px; margin-bottom: 12px; }
  .page-break { page-break-before: always; }
  footer { margin-top: 18px; font-size: 11px; color:#7a6a60; text-align:center; }
</style></head>
<body>
  <header class="sheet">
    <img src="${SOMAIYA_LOGO_DATA_URI}" alt="Somaiya" />
    <div>
      <div class="title">Somaiya Vidyavihar University</div>
      <div class="sub">K. J. Somaiya Institute of Technology</div>
    </div>
  </header>
  <h1>${escapeHtml(paper.course_code)} — ${escapeHtml(paper.course_name)}</h1>
  <div class="meta">${meta}</div>
  <div class="rules"><span>Duration: ${Math.floor(paper.duration_minutes / 60)}h ${paper.duration_minutes % 60}m</span><span>Max Marks: ${paper.max_marks}</span></div>
  ${outcomesBlock}
  ${sets}
  <footer>Generated by Paper Path</footer>
</body></html>`;
}

/** Opens the exam copy in a new window and sends it straight to the printer. */
export function printPaper(paper: ExportablePaper) {
  const html = buildPaperHtml(paper, { includeCourseOutcomes: false });
  const win = window.open("", "_blank", "width=900,height=1100");
  if (!win) return false;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
  return true;
}

export function downloadWord(paper: ExportablePaper) {
  const html = buildPaperHtml(paper, { includeCourseOutcomes: false });
  const blob = new Blob(["\ufeff", html], { type: "application/msword" });
  triggerDownload(blob, `${paper.course_code || "paper"}-exam-copy.doc`);
}

async function logoPng(): Promise<string | null> {
  try {
    const img = new Image();
    img.src = SOMAIYA_LOGO_DATA_URI;
    await new Promise((resolve, reject) => {
      img.onload = resolve;
      img.onerror = reject;
    });
    const canvas = document.createElement("canvas");
    canvas.width = 520;
    canvas.height = 144;
    const ctx = canvas.getContext("2d");
    if (!ctx) return null;
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/png");
  } catch {
    return null;
  }
}

export async function downloadPdf(paper: ExportablePaper) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 46;
  const width = doc.internal.pageSize.getWidth();
  let y = margin;

  const png = await logoPng();
  if (png) doc.addImage(png, "PNG", margin, y, 150, 41);
  doc.setTextColor(123, 20, 22);
  doc.setFont("times", "bold").setFontSize(12);
  doc.text("Somaiya Vidyavihar University", margin + 165, y + 18);
  doc.setFont("times", "normal").setFontSize(10).setTextColor(90, 76, 68);
  doc.text("K. J. Somaiya Institute of Technology", margin + 165, y + 33);
  y += 52;
  doc.setDrawColor(123, 20, 22).setLineWidth(1.2).line(margin, y, width - margin, y);
  y += 22;

  doc.setTextColor(30, 26, 24).setFont("times", "bold").setFontSize(14);
  doc.text(`${paper.course_code} — ${paper.course_name}`, margin, y);
  y += 16;
  doc.setFont("times", "normal").setFontSize(10);
  const meta = [
    paper.class_name,
    paper.semester_label ? `Semester ${paper.semester_label}` : "",
    paper.academic_year_label ?? "",
    paper.exam_type,
  ]
    .filter(Boolean)
    .join("  •  ");
  doc.text(meta, margin, y);
  y += 14;
  doc.text(
    `Duration: ${Math.floor(paper.duration_minutes / 60)}h ${paper.duration_minutes % 60}m        Max Marks: ${paper.max_marks}`,
    margin,
    y,
  );
  y += 20;

  const lineHeight = 13;
  const nextPage = () => {
    doc.addPage();
    y = margin;
  };

  paper.sets.forEach((set, index) => {
    if (index > 0) nextPage();
    doc.setFont("times", "bold").setFontSize(12);
    doc.text(set.label, margin, y);
    y += 16;
    doc.setFont("times", "normal").setFontSize(11);
    set.questions.forEach((q) => {
      const text = doc.splitTextToSize(`${q.no}. ${q.text}`, width - margin * 2 - 60) as string[];
      if (y + text.length * lineHeight > doc.internal.pageSize.getHeight() - margin) nextPage();
      doc.text(text, margin, y);
      doc.text(`[${q.marks}]`, width - margin - 30, y);
      y += text.length * lineHeight + 6;
    });
  });

  doc.save(`${paper.course_code || "paper"}-exam-copy.pdf`);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
